[package]
name = "eschec"
version = "0.1.0"
edition = "2021"

[dependencies]
color-backtrace = "0.7.0"
miette = { version = "7.5.0", features = ["fancy"] }
rand = "0.9.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
