[package]
name = "eschec"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
color-backtrace = "0.7.0"
miette = { version = "7.5.0", features = ["fancy"] }
rand = { version = "0.9.0", optional = true }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[features]
default = []
rand = ["dep:rand"]
