[package]
name = "eschec"
version = "0.1.0"
edition = "2024"
description = "A chess suite written in rust"
authors = [ "Akira" ]

[profile.release]
debug = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
color-backtrace = "0.7.0"
const_format = { version = "0.2.34", features = ["fmt"] }
miette = { version = "7.5.0", features = ["fancy"] }
rand = { version = "0.9.0", optional = true }
shell-words = "1.1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[features]
default = []
random = ["dep:rand"]
