[package]
name = "eschec"
version = "0.1.0"
edition = "2024"
description = "A chess suite written in rust"
authors = ["Akira"]

[profile.release]
debug = true
lto = "thin"
codegen-units = 1
panic = "abort"
opt-level = 3

[profile.release-dhat]
inherits = "release"
debug = 1

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
color-backtrace = "0.7.0"
dhat = { version = "0.3.3", optional = true }
miette = { version = "7.5.0", features = ["fancy"] }
rand = { version = "0.9.0", optional = true }
shell-words = "1.1.0"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
criterion = "0.6.0"

[features]
default = ["simd"]
random = ["dep:rand"]
dhat-heap = ["dep:dhat"]
simd = []

[[bench]]
name = "board_benches"
harness = false

[[bench]]
name = "engine_benches"
harness = false

[[bench]]
name = "primitive_benches"
harness = false
