#![allow(clippy::unreadable_literal)]
//! This file provides access to the pre-generated constants for magic bitboard move generation.
//! The constants themselves are in magic_constants.rs, which is generated by the magic-gen binary.

use crate::board::components::BitBoard;

/// Represents a pre-computed magic bitboard entry for a single square.
#[derive(Default, Debug, Clone, Copy)]
pub struct MagicEntry {
    /// A mask of all squares on the attack rays, excluding edges. These are the only
    /// squares that can block the sliding piece.
    pub mask: BitBoard,
    /// The magic number used to transform the blockers bitboard into a unique index.
    pub magic: u64,
    /// A pointer to the first of this piece's attack_sets in the global attacks table.
    pub attacks: *const BitBoard,
    /// The amount to shift the transformed blockers by to get the final table index.
    pub shift: u32,
}

impl MagicEntry {
    // A default, empty magic entry used for initializing the MoveTables struct.
    pub const EMPTY_MAGIC: MagicEntry = MagicEntry {
        mask: BitBoard(0),
        magic: 0,
        attacks: std::ptr::null(),
        shift: 0,
    };
}

// This line includes the generated constants file at compile time.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/src/moves/magic_constants.rs"
));
